/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package huawei.shared;

public final class R {
    public static final class dimen {
        public static int padding_large = 0x7f080001;
        public static int padding_medium = 0x7f080002;
        public static int padding_small = 0x7f080003;
    }
    public static final class drawable {
        public static int ic_action_search = 0x7f090001;
        public static int ic_launcher = 0x7f090002;
    }
    public static final class id {
        public static int menu_settings = 0x7f0c0001;
        public static int newFileName = 0x7f0c0002;
        public static int rename = 0x7f0c0003;
        public static int webView = 0x7f0c0004;
    }
    public static final class layout {
        public static int activity_main = 0x7f0f0001;
        public static int webview_main = 0x7f0f0002;
    }
    public static final class menu {
        public static int activity_main = 0x7f100001;
    }
    public static final class string {
        public static int app_name = 0x7f150001;
        public static int hello_world = 0x7f150002;
        public static int menu_settings = 0x7f150003;
        public static int title_activity_main = 0x7f150004;
    }
    public static final class style {
        public static int AppTheme = 0x7f160001;
    }
}
